### ISSUE TITLE
Can't open on M1 iMac (Monterey 12.2 Beta)

### ISSUE THREAD

**Issue by chentao1006** [v2ex/launcher#1]
<img width="500" alt="iShot2022-01-04 17 48 08" src="https://user-images.githubusercontent.com/421638/148040644-6094ab4c-1b81-41d5-9c8b-edfacf674b66.png">

**Comment by livid** [comment]
Your macOS system version?

**Comment by livid** [comment]
OK. I saw it on your issue title. I will look into this now.

**Comment by livid** [comment]
It may have something to do with your unzip program. Try re-download it with Safari?

**Comment by livid** [comment]
Have you got it working?

**Comment by chentao1006** [comment]
> Have you got it working?

Yes, it's working this time. Thank you.
