### ISSUE TITLE
task execute error

### ISSUE THREAD

**Issue by tasen** [v2ex/launcher#2]
nginx -g "daemon off;"

**Comment by livid** [comment]
Can you send us a screenshot of your project editing window?

**Comment by tasen** [comment]
task config
<img width="600" alt="task_config" src="https://user-images.githubusercontent.com/1849185/148223930-62d786e1-cf1b-407b-b3e6-2af82fb89b55.png">

task log
<img width="900" alt="task_log" src="https://user-images.githubusercontent.com/1849185/148223890-b59cb521-c0ab-4812-ba69-37c5827271eb.png">

**Comment by livid** [comment]
Thanks a lot. It looks like an issue in handling arguments with quotes. We'll fix it ASAP.

**Comment by livid** [comment]
@tasen 

In update 1.0.1 we have fixed this issue. Now `nginx -g "daemon off;"` is working.

**Comment by tasen** [comment]
Thanks a lot.
