### ISSUE TITLE
Output area is white in dark mode

### ISSUE THREAD

**Issue by chentao1006** [v2ex/launcher#5]
<img width="936" alt="iShot2022-01-08 20 53 06" src="https://user-images.githubusercontent.com/421638/148644894-552c6bce-f817-46ee-86d6-cf47ffdddfaf.png">

**Comment by kailuo** [comment]
Right, output area now has very limited support for themes and font settings (It's just [solarized](https://ethanschoonover.com/solarized/) theme now in reverse for better contrast).

**Comment by livid** [comment]
Thanks! We will add a setting for choosing themes.

**Comment by livid** [comment]
@kailuo I implemented the initial support for switching themes. It is created as PR #8.

**Comment by kailuo** [comment]
👌

**Comment by livid** [comment]
@chentao1006 We have released 1.0.2 today with initial support for switching themes.

Now you can choose from these options for theme:

<img width="384" alt="Screen Shot 2022-01-12 at 1 08 52 PM" src="https://user-images.githubusercontent.com/11427/149221707-0e254d16-5b88-46d3-af92-a167b27ac23a.png">
